### ISSUE TITLE
[Week1 - StudyTodo] 강의 학습

### ISSUE THREAD

**Issue by 2Ruk** [2Ruk/nestjs-study#6]
- 강의의 코드를 작성한 자신의 Github Repository Link를 작성해주세요.
- 또는, 여기 Repo에서 코드를 작성해서 올려도 됩니다! ( 이름 기반 folder 생성 후 project init ) 
  - 하지만 nestjs cli 설치 시 git이 자동으로 설치가 되기에 --skip-git 이라는 option을 알아봐야해요!

**Comment by 2Ruk** [comment]
- 예시 ) 
링크: https://xxxxxxxxx

**Comment by hyun9360** [comment]
링크: https://github.com/hyun9360/nestjs-board-app

**Comment by HONG33333** [comment]
https://github.com/HONG33333/nest-zzicmuk

**Comment by 2Ruk** [comment]
https://github.com/2Ruk/nestjs-ttt

**Comment by iambom** [comment]
https://github.com/iambom/nestjs-board-app

**Comment by DaHoon06** [comment]
https://github.com/DaHoon06/nestjs-study

**Comment by 2Ruk** [comment]
@DaHoon06 Repository에 이거 뭐죠!?!?! 

```
  constructor() {
    super(undefined, undefined, undefined);
  }
```

**Comment by justinaus** [comment]
https://github.com/justinaus/nestjs-board-study

**Comment by 2Ruk** [comment]
@justinaus 아주 goood!! 이네요!! 
중간에 env흔적을 봤는데 요건 dot env library나  [ConfigService](https://docs.nestjs.com/techniques/configuration) 를 보시면 적용하실 수 있을거에요!
